### ISSUE TITLE
Request and Response source files are missing from the repository, can't compile

### ISSUE THREAD

**Issue by ktgt** [cacafaca/CounterStrikeAlerter#2]
Hi Nemanja,
I found another commit issue. Files Request.cs and Response.cs in CSA.ViewModel project are missing - not added to repository.
Please commit them, otherwise I can't compile.

![image](https://cloud.githubusercontent.com/assets/17131884/12962272/0e0aea82-d045-11e5-8a2b-ae3fe00d1765.png)

Regards,
Ivan

**Comment by cacafaca** [comment]
Dear Ivan,

I've added files. Please try to build again.

**Comment by ktgt** [comment]
Thanks Nemanja,
It works now!

Regards,
Ivan
